#!/bin/bash

NAME="MME"                                     # Name of the application
SOCKFILE=run/gunicorn.sock                     # We will communicte using this unix socket
USER=root                                      # The user to run as
GROUP=root                                     # The group to run as
NUM_WORKERS=3                                  # How many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=MME.settings.production # Which settings file should Django use
DJANGO_WSGI_MODULE=MME.wsgi                    # WSGI module name

echo "Starting $NAME as `whoami`"

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start Django Unicorn
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
