# Generated by Django 3.1.13 on 2021-09-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misionalpage',
            name='link_list',
        ),
    ]
