# Generated by Django 3.1.13 on 2021-09-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0008_fuentesnoconvencionalesenergiarenovablepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuentesnoconvencionalesenergiarenovablepage',
            name='intro_title',
            field=models.CharField(default='Fuentes No Convencionales de Energía Renovable - FNCER', max_length=254, verbose_name='Título de la sección'),
        ),
        migrations.AlterField(
            model_name='fuentesnoconvencionalesenergiarenovablepage',
            name='second_intro_title',
            field=models.CharField(default='FNCER en Colombia', max_length=254, verbose_name='Título de la sección'),
        ),
        migrations.AlterField(
            model_name='fuentesnoconvencionalesenergiarenovablepage',
            name='third_intro_title',
            field=models.CharField(default='Recursos Energéticos Distribuidos', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
