# Generated by Django 3.1.13 on 2021-10-12 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('misional', '0013_cierrebrechaspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrebrechaspage',
            name='featured_link',
        ),
        migrations.AddField(
            model_name='cierrebrechaspage',
            name='document_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Documento'),
        ),
    ]
