# Generated by Django 3.1.13 on 2021-10-13 16:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0014_auto_20211011_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrebrechaspage',
            name='cards',
            field=wagtail.core.fields.StreamField([('Brechas', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Título que describe el elemento', label='Título del Elemento', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen que representa el elemento', label='Imagen', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', label='Texto alternativo', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local.', label='Link a página local:', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa.Si este campo está completo, no se tendrá en cuenta el link a página local.', label='Link a página externa:', required=False))]))], blank=True, verbose_name='¿En qué consiste el Cierre de brechas?'),
        ),
    ]
