# Generated by Django 3.1.13 on 2021-11-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0017_accesoenergiapage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesoenergiapage',
            name='intro_title',
            field=models.CharField(default='Acceso a energía', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
