# Generated by Django 3.1.13 on 2021-11-24 20:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('misional', '0022_auto_20211124_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuenasPracticaIndexPage',
            new_name='BuenasPracticasIndexPage',
        ),
    ]
