# Generated by Django 3.1.13 on 2021-11-25 11:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('misional', '0026_auto_20211124_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiudadesEnergeticasPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('link_list', wagtail.core.fields.StreamField([('Ciudades', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Descripción principal', label='Descripción', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=False, help_text='Imagen', label='Imagen', required=False)), ('alt_text', wagtail.core.blocks.TextBlock(blank=False, help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', label='Texto alternativo', required=False)), ('align', wagtail.core.blocks.ChoiceBlock(choices=[('true', 'Izquierda')], help_text='Si esta opción esta activa, la imagen se alineara a la izquierda, por defecto se alineará a la derecha.', label='Alinear imagen a la izquierda', required=False))]))], blank=True, verbose_name='Ciudades Energéticas')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
