# Generated by Django 3.1.13 on 2021-11-25 11:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0027_ciudadesenergeticaspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadesenergeticaspage',
            name='link_list',
            field=wagtail.core.fields.StreamField([('Ciudades', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Descripción del elemento', icon='fa-paragraph', label='Descripción', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=False, help_text='Imagen', label='Imagen', required=False)), ('alt_text', wagtail.core.blocks.TextBlock(blank=False, help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', label='Texto alternativo', required=False)), ('align', wagtail.core.blocks.ChoiceBlock(choices=[('true', 'Izquierda')], help_text='Si esta opción esta activa, la imagen se alineara a la izquierda, por defecto se alineará a la derecha.', label='Alinear imagen a la izquierda', required=False))]))], blank=True, verbose_name='Ciudades Energéticas'),
        ),
    ]
