# Generated by Django 3.1.13 on 2021-11-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0037_auto_20211130_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datossectorpage',
            name='link_video',
        ),
        migrations.AddField(
            model_name='datossectorpage',
            name='link_pbi',
            field=models.URLField(blank=True, help_text='Link de acceso al tablero Power BI', verbose_name='Link tablero Power BI'),
        ),
    ]
