# Generated by Django 3.1.13 on 2021-12-01 02:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0040_transformacionminerapage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformacionminerapage',
            name='menu_list',
            field=wagtail.core.fields.StreamField([('Items', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('main_description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True))]))], blank=True, verbose_name='Lineamientos y Políticas'),
        ),
    ]
