# Generated by Django 3.1.13 on 2021-12-02 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('misional', '0042_diversificacionproduccionmineralespage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MineriaPage',
        ),
    ]
