# Generated by Django 3.1.13 on 2021-12-02 00:32

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0044_legalidadpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalidadpage',
            name='menu_list',
            field=wagtail.core.fields.StreamField([('Items', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('main_description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True))]))], blank=True, verbose_name='Casos de éxito'),
        ),
        migrations.AddField(
            model_name='legalidadpage',
            name='menu_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AlterField(
            model_name='legalidadpage',
            name='intro_title',
            field=models.CharField(default='Legalidad', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
