# Generated by Django 3.1.13 on 2021-12-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0053_auto_20211201_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionamientosectorpage',
            name='link_list_title',
            field=models.CharField(default='Grupos Transversales de la Dirección', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
