# Generated by Django 3.1.13 on 2021-12-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('misional', '0069_auto_20211204_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacidadgeneracionenergiaelectricapage',
            name='image_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='capacidadgeneracionenergiaelectricapage',
            name='infographic',
            field=models.ForeignKey(blank=True, help_text='Infografía', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Infografías'),
        ),
        migrations.AlterField(
            model_name='capacidadgeneracionenergiaelectricapage',
            name='intro_title',
            field=models.CharField(default=' Capacidad de generación de energía eléctrica a partir de FNCER', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
