# Generated by Django 3.1.13 on 2021-12-04 21:10

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0072_auto_20211204_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacidadgeneracionenergiaelectricapage',
            name='intro_two',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Bloque de texto', null=True, verbose_name='Bloque de texto'),
        ),
        migrations.AddField(
            model_name='construccionproyectoseolicospage',
            name='intro_two',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Bloque de texto', null=True, verbose_name='Bloque de texto'),
        ),
        migrations.AlterField(
            model_name='construccionproyectoseolicospage',
            name='intro_title',
            field=models.CharField(default=' Construcción de proyectos eólicos en La Guajira', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
