# Generated by Django 3.1.13 on 2021-12-04 21:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('misional', '0075_auto_20211204_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='marconormativoaprovechamientopage',
            name='document_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='marconormativoaprovechamientopage',
            name='intro_image',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Bloque de texto', null=True, verbose_name='Bloque de texto'),
        ),
    ]
