# Generated by Django 3.1.13 on 2021-12-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('misional', '0076_auto_20211204_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='marconormativoaprovechamientopage',
            name='image_alt_text',
            field=models.TextField(blank=True, help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', verbose_name='Texto alternativo'),
        ),
        migrations.AlterField(
            model_name='marconormativoaprovechamientopage',
            name='infographic',
            field=models.ForeignKey(blank=True, help_text='Imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='marconormativoaprovechamientopage',
            name='intro_title',
            field=models.CharField(default='Marco normativo del aprovechamiento geotérmico', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
