# Generated by Django 3.1.13 on 2021-12-04 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('misional', '0077_auto_20211204_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marconormativoaprovechamientopage',
            name='document_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Documento'),
        ),
    ]
