# Generated by Django 3.1.13 on 2021-12-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0080_auto_20211204_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementacionmisionpage',
            name='images_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='implementacionmisionpage',
            name='video_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
    ]
