# Generated by Django 3.1.13 on 2021-12-05 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('misional', '0085_auto_20211204_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='subastasenergiasrenovablespage',
            name='subasta_button_title',
            field=models.CharField(blank=True, help_text='Título del botón más información que será presentado al público, longitud máxima 20 caracteres', max_length=20, null=True, verbose_name='Título botón más información'),
        ),
        migrations.AddField(
            model_name='subastasenergiasrenovablespage',
            name='subasta_list',
            field=models.ForeignKey(blank=True, help_text='Seleccione la página del índice de subastas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Índice de noticias'),
        ),
        migrations.AddField(
            model_name='subastasenergiasrenovablespage',
            name='subasta_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
    ]
