# Generated by Django 3.1.13 on 2021-12-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0087_funcionespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionespage',
            name='intro_title',
            field=models.CharField(default='Funciones', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
