# Generated by Django 3.1.13 on 2021-12-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0089_energiaelectricapage_energiafuncionamientosectorpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='alt_text_one',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='alt_text_three',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='alt_text_two',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='image_pbi_one',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='image_pbi_two',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='image_two',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='intro_one',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='intro_three',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='intro_two',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='link_pbi_one',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='link_pbi_two',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='link_video_one',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='link_video_three',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='link_video_two',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='title_one',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='title_pbi',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='title_three',
        ),
        migrations.RemoveField(
            model_name='energiafuncionamientosectorpage',
            name='title_two',
        ),
    ]
