# Generated by Django 3.1.13 on 2021-12-09 21:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('misional', '0092_auto_20211209_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='energiafuncionamientosectorpage',
            name='alt_text_three',
            field=models.TextField(blank=True, help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', verbose_name='Texto alternativo'),
        ),
        migrations.AddField(
            model_name='energiafuncionamientosectorpage',
            name='image_three',
            field=models.ForeignKey(blank=True, help_text='Imagen que representa la sección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='energiafuncionamientosectorpage',
            name='intro_three',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='energiafuncionamientosectorpage',
            name='link_video_three',
            field=models.URLField(blank=True, help_text='Si completa este campo, la imagen no será presentada. El link requerido debe tener el siguiente formato https://www.youtube.com/embed/lkizzbz2ci85', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='energiafuncionamientosectorpage',
            name='title_three',
            field=models.CharField(default='¿Qué hacemos?', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
