# Generated by Django 3.1.13 on 2021-12-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('misional', '0093_auto_20211209_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='energiafuncionamientosectorpage',
            name='image_pbi_one',
            field=models.ForeignKey(blank=True, help_text='Imagen que representa la sección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='energiafuncionamientosectorpage',
            name='link_pbi_one',
            field=models.URLField(blank=True, help_text='Link de acceso al tablero Power BI', verbose_name='Link tablero Power BI'),
        ),
        migrations.AddField(
            model_name='energiafuncionamientosectorpage',
            name='title_pbi',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
    ]
