# Generated by Django 3.1.13 on 2021-12-09 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('misional', '0094_auto_20211209_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='energiafuncionamientosectorpage',
            name='image_pbi_two',
            field=models.ForeignKey(blank=True, help_text='Imagen que representa la sección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='energiafuncionamientosectorpage',
            name='link_pbi_two',
            field=models.URLField(blank=True, help_text='Link de acceso al tablero Power BI', verbose_name='Link tablero Power BI'),
        ),
    ]
