# Generated by Django 3.1.13 on 2021-12-25 16:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0106_auto_20211224_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifassubsidiosrednacionalpage',
            name='cards_list',
            field=wagtail.core.fields.StreamField([('Documentos', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Titulo del mecanismo de participación', label='Titulo', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Descripción del mecanismo de participación', label='Descripción del elemento', required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(help_text='Seleccione un documento', label='Documento', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local.', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa.Si este campo está completo, no se tendrá en cuenta el link a página local.', label='Link a página externa:', required=False))]))], blank=True, verbose_name='Documentos'),
        ),
    ]
