# Generated by Django 3.1.13 on 2021-12-25 16:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('misional', '0111_ffsriage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ffsriage',
            new_name='FfsriPage',
        ),
    ]
