# Generated by Django 3.1.13 on 2022-03-16 04:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0117_auto_20220209_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasfrecuentesreglamentostecnicossectorenergiaelectricapage',
            name='element_list',
            field=wagtail.core.fields.StreamField([('Lista', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Nombre del elemento', label='Nombre', required=True)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono, solo imágenes en formato SVG.', label='Icono', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Descripción del elemento', icon='fa-paragraph', label='Descripción', required=True))]))], blank=True, verbose_name='Preguntas Frecuentes'),
        ),
    ]
