# Generated by Django 3.1.13 on 2022-03-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0118_gestionsocialambientalpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionsocialambientalpage',
            name='sostenib_list_title',
        ),
    ]
