# Generated by Django 3.1.13 on 2022-03-16 04:57

import apps.misional.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0118_preguntasfrecuentesreglamentostecnicossectorenergiaelectricapage_element_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasfrecuentesreglamentostecnicossectorenergiaelectricapage',
            name='element_list',
            field=wagtail.core.fields.StreamField([('Lista', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Nombre del elemento', label='Nombre', required=True)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono, solo imágenes en formato SVG.', label='Icono', required=True)), ('subitems', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(blank=False, help_text='Título del elemento', label='Título del elemento', required=True)), ('subitems_acordeon', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=False, help_text='Título del elemento', label='Título del elemento', required=True)), ('subitems_acordeon_body', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.RichTextBlock(help_text='Breve descripción', icon='fa-paragraph', label='Descripción', required=False))]), blank=True, help_text='Lista de elementos que se presentaran', label='Lista de elementos', required=False))]), blank=True, help_text='Lista de elementos', icon='list-ul', label='Lista de elementos', required=False))], closed=False, icon='link', value_class=apps.misional.blocks.LinkStructValue), blank=True, help_text='Lista de elementos', label='Lista de elementos', required=False))]))], blank=True, verbose_name='Preguntas Frecuentes'),
        ),
    ]
