# Generated by Django 3.1.13 on 2022-03-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('misional', '0120_oficinaasuntosambientalessosteniblespage'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficinaasuntosambientalessosteniblespage',
            name='first_image',
            field=models.ForeignKey(blank=True, help_text='Imagen que representa la sección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen'),
        ),
    ]
