# Generated by Django 3.1.13 on 2022-03-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0121_auto_20220316_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntasfrecuentesreglamentostecnicossectorenergiaelectricapage',
            name='actions_list',
        ),
        migrations.RemoveField(
            model_name='preguntasfrecuentesreglamentostecnicossectorenergiaelectricapage',
            name='assigned_tabs_list',
        ),
        migrations.RemoveField(
            model_name='preguntasfrecuentesreglamentostecnicossectorenergiaelectricapage',
            name='assigned_tabs_list_four',
        ),
        migrations.RemoveField(
            model_name='preguntasfrecuentesreglamentostecnicossectorenergiaelectricapage',
            name='assigned_tabs_list_three',
        ),
        migrations.RemoveField(
            model_name='preguntasfrecuentesreglamentostecnicossectorenergiaelectricapage',
            name='assigned_tabs_list_title',
        ),
        migrations.RemoveField(
            model_name='preguntasfrecuentesreglamentostecnicossectorenergiaelectricapage',
            name='assigned_tabs_list_title_four',
        ),
        migrations.RemoveField(
            model_name='preguntasfrecuentesreglamentostecnicossectorenergiaelectricapage',
            name='assigned_tabs_list_title_three',
        ),
        migrations.RemoveField(
            model_name='preguntasfrecuentesreglamentostecnicossectorenergiaelectricapage',
            name='assigned_tabs_list_title_two',
        ),
        migrations.RemoveField(
            model_name='preguntasfrecuentesreglamentostecnicossectorenergiaelectricapage',
            name='assigned_tabs_list_two',
        ),
    ]
