# Generated by Django 3.1.13 on 2022-03-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0127_auto_20220328_1557'),
        ('misional', '0122_auto_20220316_2108'),
    ]

    operations = [
    ]
