# Generated by Django 3.1.13 on 2022-04-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0129_auto_20220330_0057'),
        ('misional', '0123_auto_20220331_1435'),
    ]

    operations = [
    ]
