# Generated by Django 3.1.13 on 2022-04-06 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('misional', '0137_auto_20220405_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conoceunidadresultadospage',
            name='button_title',
        ),
        migrations.RemoveField(
            model_name='conoceunidadresultadospage',
            name='document_mapa',
        ),
        migrations.RemoveField(
            model_name='conoceunidadresultadospage',
            name='link_mapa',
        ),
        migrations.AddField(
            model_name='unidadresultadospage',
            name='button_title',
            field=models.CharField(default='', help_text='Título del boton', max_length=254, verbose_name='Título del boton'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadresultadospage',
            name='document_mapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Documento del mapa'),
        ),
        migrations.AddField(
            model_name='unidadresultadospage',
            name='link_mapa',
            field=models.URLField(blank=True, verbose_name='Link del mapa'),
        ),
    ]
