# Generated by Django 3.1.13 on 2022-04-06 05:06

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0138_auto_20220405_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conoceunidadresultadospage',
            name='featured_link',
        ),
        migrations.RemoveField(
            model_name='conoceunidadresultadospage',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='conoceunidadresultadospage',
            name='text_link',
        ),
        migrations.AddField(
            model_name='conoceunidadresultadospage',
            name='intro_objetivos',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='conoceunidadresultadospage',
            name='objetivos_title',
            field=models.CharField(default='Objetivos transformacionales minero-energéticos', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
