# Generated by Django 3.1.13 on 2022-04-08 05:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20211125_1214'),
        ('misional', '0141_conoceunidadresultadospage_link_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadResultadosNoticiaSectorRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidad_resultados_sector_relationship', to='misional.unidadresultadopage')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidad_resultados_sector_relationship', to='common.sector')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UnidadResultadoNoticiaSectorRelationship',
        ),
    ]
