# Generated by Django 3.1.13 on 2022-04-11 19:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0144_conoceunidadresultadospage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conoceunidadresultadospage',
            name='body',
        ),
        migrations.AddField(
            model_name='unidadresultadopage',
            name='body',
            field=wagtail.core.fields.StreamField([('image_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(form_classname='title', label='Título', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=True))], label='Bloque de imagen'))], default='', verbose_name='Imágenes de la galería'),
            preserve_default=False,
        ),
    ]
