# Generated by Django 3.1.13 on 2022-04-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misional', '0146_auto_20220411_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadresultadopage',
            name='intro_title',
            field=models.CharField(default='Noticia', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
