# Generated by Django 3.1.13 on 2022-04-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infografiapage',
            name='introduction',
            field=models.TextField(help_text='Texto que describe la infografía', verbose_name='Descripción'),
        ),
    ]
