# Generated by Django 3.1.7 on 2021-07-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala_prensa', '0002_auto_20210715_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoticiaPeopleRelationship',
            new_name='NoticiaAutorRelationship',
        ),
    ]
