# Generated by Django 3.1.7 on 2021-07-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_prensa', '0003_auto_20210715_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='autor',
            name='organization_title',
            field=models.CharField(default='MINENERGÍA', max_length=254, verbose_name='Nombre de la Organización'),
        ),
    ]
