# Generated by Django 3.1.7 on 2021-07-16 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala_prensa', '0013_auto_20210715_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticiasectorrelationship',
            old_name='autor',
            new_name='sector',
        ),
    ]
