# Generated by Django 3.1.7 on 2021-07-31 15:23

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('sala_prensa', '0017_galeriaautorrelationship_galeriaindexpage_galeriapage_galeriapagetag_galeriasectorrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriapage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='sala_prensa.GaleriaPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
