# Generated by Django 3.1.7 on 2021-07-31 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('sala_prensa', '0018_auto_20210731_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='prensapage',
            name='gallery_list',
            field=models.ForeignKey(blank=True, help_text='Seleccione la página del índice de noticias', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Índice de noticias'),
        ),
    ]
