# Generated by Django 3.1.7 on 2021-07-31 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('sala_prensa', '0021_auto_20210731_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infografiapage',
            name='image',
            field=models.ForeignKey(help_text='Solo modo cuadrado; ancho horizontal entre 1080px y 1080px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Infografía'),
        ),
        migrations.AlterField(
            model_name='infografiapage',
            name='introduction',
            field=models.TextField(help_text='Texto que describe la infografía', verbose_name='Introducción'),
        ),
    ]
