# Generated by Django 3.1.7 on 2021-07-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_prensa', '0022_auto_20210731_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infografiapage',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Ciudad'),
        ),
    ]
