# Generated by Django 3.1.7 on 2021-07-31 23:26

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('sala_prensa', '0023_auto_20210731_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriapage',
            name='body',
            field=wagtail.core.fields.StreamField([('image_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(form_classname='title', label='Título', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=True))], label='Bloque de imagen'))], verbose_name='Imágenes de la galería'),
        ),
        migrations.AlterField(
            model_name='galeriapage',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='galeriapage',
            name='date_published',
            field=models.DateField(null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='galeriapage',
            name='image',
            field=models.ForeignKey(help_text='Solo modo horizontal; ancho horizontal entre 1000px y 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='galeriapage',
            name='introduction',
            field=models.TextField(help_text='Texto que describe la galeria', verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='galeriapage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(help_text='A comma-separated list of tags.', through='sala_prensa.GaleriaPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='infografiapage',
            name='date_published',
            field=models.DateField(null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='infografiapage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(help_text='A comma-separated list of tags.', through='sala_prensa.InfografiaPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', label='Bloque de párrafo', template='news_blocks/paragraph_block.html')), ('image_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(form_classname='title', label='Título', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=True)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(label='Texto de la imagen', required=True)), ('text', wagtail.core.blocks.TextBlock(label='Cita', required=False))], label='Bloque de imagen')), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(label='Cita')), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='Ej. Mary Berry', required=False))], label='Bloque de citación')), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-link', label='Bloque de enalce', template='news_blocks/embed_block.html'))], verbose_name='Cuerpo de la noticia'),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='date_published',
            field=models.DateField(null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='image',
            field=models.ForeignKey(help_text='Solo modo horizontal; ancho horizontal entre 1000px y 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='introduction',
            field=models.TextField(help_text='Texto que describe la noticia', verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(help_text='A comma-separated list of tags.', through='sala_prensa.NoticiaPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
