# Generated by Django 3.1.7 on 2021-07-31 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('sala_prensa', '0024_auto_20210731_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='prensapage',
            name='infographics_list',
            field=models.ForeignKey(blank=True, help_text='Seleccione la página del índice de noticias', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Índice de noticias'),
        ),
    ]
