# Generated by Django 3.1.7 on 2021-08-01 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('sala_prensa', '0028_auto_20210731_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='prensapage',
            name='audios_list',
            field=models.ForeignKey(blank=True, help_text='Seleccione la página del índice de videos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Índice de videos'),
        ),
        migrations.AlterField(
            model_name='prensapage',
            name='gallery_list',
            field=models.ForeignKey(blank=True, help_text='Seleccione la página del índice de galeria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Índice de galeria'),
        ),
        migrations.AlterField(
            model_name='prensapage',
            name='infographics_list',
            field=models.ForeignKey(blank=True, help_text='Seleccione la página del índice de infografías', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Índice de infografías'),
        ),
        migrations.AlterField(
            model_name='prensapage',
            name='videos_list',
            field=models.ForeignKey(blank=True, help_text='Seleccione la página del índice de videos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Índice de videos'),
        ),
    ]
