# Generated by Django 3.1.7 on 2021-08-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('sala_prensa', '0030_auto_20210731_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentopage',
            name='image',
            field=models.ForeignKey(help_text='Imagen de presentación para el documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen del documento'),
        ),
        migrations.AlterField(
            model_name='documentopage',
            name='document_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Documento'),
        ),
    ]
