# Generated by Django 3.1.13 on 2021-09-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_prensa', '0034_prensapage_events_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='prensapage',
            name='audios_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='documents_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='events_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='gallery_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='infographics_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='news_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='videos_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
    ]
