# Generated by Django 3.1.13 on 2021-09-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_prensa', '0037_auto_20210903_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='prensapage',
            name='podcast_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='podcast_url',
            field=models.URLField(blank=True, help_text='Link a página de podcast', verbose_name='Link a página de podcast'),
        ),
    ]
