# Generated by Django 3.1.13 on 2021-09-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_prensa', '0038_auto_20210903_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='prensapage',
            name='podcast_iframe_url',
            field=models.URLField(blank=True, help_text='URL iframe Podcats', verbose_name='URL iframe Podcats'),
        ),
    ]
