# Generated by Django 3.1.13 on 2021-09-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_prensa', '0039_prensapage_podcast_iframe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prensapage',
            name='podcast_iframe_url',
            field=models.URLField(blank=True, help_text='URL iframe Podcats', max_length=2000, verbose_name='URL iframe Podcats'),
        ),
    ]
