# Generated by Django 3.1.13 on 2021-09-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_prensa', '0040_auto_20210903_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='prensapage',
            name='audios_button_title',
            field=models.CharField(blank=True, help_text='Título del botón más información que será presentado al público, longitud máxima 20 caracteres', max_length=20, null=True, verbose_name='Título botón más información'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='documents_button_title',
            field=models.CharField(blank=True, help_text='Título del botón más información que será presentado al público, longitud máxima 20 caracteres', max_length=20, null=True, verbose_name='Título botón más información'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='events_button_title',
            field=models.CharField(blank=True, help_text='Título del botón más información que será presentado al público, longitud máxima 20 caracteres', max_length=20, null=True, verbose_name='Título botón más información'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='gallery_button_title',
            field=models.CharField(blank=True, help_text='Título del botón más información que será presentado al público, longitud máxima 20 caracteres', max_length=20, null=True, verbose_name='Título botón más información'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='infographics_button_title',
            field=models.CharField(blank=True, help_text='Título del botón más información que será presentado al público, longitud máxima 20 caracteres', max_length=20, null=True, verbose_name='Título botón más información'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='news_button_title',
            field=models.CharField(blank=True, help_text='Título del botón más información que será presentado al público, longitud máxima 20 caracteres', max_length=20, null=True, verbose_name='Título botón más información'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='podcats_button_title',
            field=models.CharField(blank=True, help_text='Título del botón más información que será presentado al público, longitud máxima 20 caracteres', max_length=20, null=True, verbose_name='Título botón más información'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='videos_button_title',
            field=models.CharField(blank=True, help_text='Título del botón más información que será presentado al público, longitud máxima 20 caracteres', max_length=20, null=True, verbose_name='Título botón más información'),
        ),
    ]
