# Generated by Django 3.1.13 on 2021-09-04 22:45

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sala_prensa', '0041_auto_20210903_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='prensapage',
            name='social_networks',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(help_text='Nombre de la red social', label='Nombre', required=True)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono de la red social, solo imágenes en formato SVG.', label='Icono', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text="Fragmento de código correspondiente al iframe o timeline de la red social. Ejemplo: <a class='twitter-timeline' data-width='400' data-height='700' href='https://twitter.com/MinEnergiaCo?ref_src=twsrc5Etfw'>Tweets por MinEnergiaCo</a> ", label='Cita', max_length=4000, null=True, required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='URL de acceso a la red social', label='Link a la red social', null=True, required=False))], blank=True, verbose_name='Redes Sociales'),
        ),
        migrations.AddField(
            model_name='prensapage',
            name='social_networks_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AlterField(
            model_name='eventopage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', label='Bloque de párrafo', template='news_blocks/paragraph_block.html')), ('image_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(form_classname='title', label='Título', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=True)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(label='Texto de la imagen', required=True)), ('text', wagtail.core.blocks.TextBlock(label='Cita', required=False))], label='Bloque de imagen')), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(help_text='No incluir comillas de inicio', label='Cita')), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='Ej. Mary Berry', required=False))], label='Bloque de citación')), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-link', label='Bloque de enalce', template='news_blocks/embed_block.html'))], verbose_name='Cuerpo del evento'),
        ),
        migrations.AlterField(
            model_name='noticiapage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph_block', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph', label='Bloque de párrafo', template='news_blocks/paragraph_block.html')), ('image_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(form_classname='title', label='Título', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen', required=True)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(label='Texto de la imagen', required=True)), ('text', wagtail.core.blocks.TextBlock(label='Cita', required=False))], label='Bloque de imagen')), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(help_text='No incluir comillas de inicio', label='Cita')), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='Ej. Mary Berry', required=False))], label='Bloque de citación')), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-link', label='Bloque de enalce', template='news_blocks/embed_block.html'))], verbose_name='Cuerpo de la noticia'),
        ),
    ]
