# Generated by Django 3.1.13 on 2021-09-04 22:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('sala_prensa', '0042_auto_20210904_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prensapage',
            name='social_networks',
            field=wagtail.core.fields.StreamField([('Red', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Nombre de la red social', label='Nombre', required=True)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono de la red social, solo imágenes en formato SVG.', label='Icono', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text="Fragmento de código correspondiente al iframe o timeline de la red social. Ejemplo: <a class='twitter-timeline' data-width='400' data-height='700' href='https://twitter.com/MinEnergiaCo?ref_src=twsrc5Etfw'>Tweets por MinEnergiaCo</a> ", label='Cita', max_length=4000, null=True, required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='URL de acceso a la red social', label='Link a la red social', null=True, required=False))]))], blank=True, verbose_name='Redes Sociales'),
        ),
    ]
