# Generated by Django 3.1.13 on 2021-11-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211117_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='board_title',
            field=models.CharField(blank=True, help_text='Título del la sección', max_length=120, null=True, verbose_name='Título del la sección'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_pbi',
            field=models.URLField(blank=True, help_text='Link de acceso al tablero Power BI', verbose_name='Link tablero Power BI'),
        ),
    ]
