# Generated by Django 3.1.13 on 2021-11-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('home', '0007_auto_20211117_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NormativaPage',
        ),
    ]
