# Generated by Django 3.1.13 on 2022-03-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_normativapage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='url_page',
            field=models.URLField(blank=True, help_text='Link de pagina', verbose_name='Link a la pagina'),
        ),
    ]
