# Generated by Django 3.1.13 on 2022-04-16 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220301_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='cierre_brechas',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='events_button_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='events_list',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='events_list_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='information_systems',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='interesting_links',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='link_pbi',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='systems_title',
        ),
    ]
