# Generated by Django 3.1.13 on 2022-04-16 23:03

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220416_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='information_systems',
            field=wagtail.core.fields.StreamField([('Sistema', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del sistema de información', label='Título', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=False, help_text='Imagen del sistema de información', label='Imagen', required=True)), ('alt_text', wagtail.core.blocks.TextBlock(blank=False, help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla).', label='Texto alternativo', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(blank=False, help_text='Complete este campo si desea enlazar este slider con una página local.', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(blank=False, help_text='Complete este campo si desea enlazar este slider con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local.', label='Link a página externa', required=False))]))], blank=True, verbose_name='Sistemas de información'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='systems_title',
            field=models.CharField(blank=True, help_text='Título del la sección', max_length=120, null=True, verbose_name='Título del la sección'),
        ),
    ]
