# Generated by Django 3.1.13 on 2022-04-19 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0015_auto_20220419_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news_button_title',
            field=models.CharField(blank=True, help_text='Título del botón más información que será presentado al público, longitud máxima 20 caracteres', max_length=20, null=True, verbose_name='Título botón más información'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_list',
            field=models.ForeignKey(blank=True, help_text='Seleccione la página del índice de noticias', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Índice de noticias'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
    ]
