# Generated by Django 3.1.13 on 2022-04-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_loginpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpage',
            name='systems_title',
            field=models.CharField(blank=True, help_text='Login', max_length=120, null=True, verbose_name='Login'),
        ),
    ]
