# Generated by Django 3.1.13 on 2021-09-05 16:47

import apps.servicio_ciudadano.blocks
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_ciudadano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciociudanopage',
            name='briefcase_list',
            field=wagtail.core.fields.StreamField([('Portafolio', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del portafolio, políticas y/o protocolos de servicio ', label='Título', required=True)), ('main_description', wagtail.core.blocks.TextBlock(help_text='Descripción principal del portafolio, políticas y/o protocolos de servicio ', label='Descripción principal ', required=True)), ('second_description', wagtail.core.blocks.TextBlock(help_text='Descripción complementaria del portafolio, políticas y/o protocolos de servicio ', label='Descripción complementaria ', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=False, help_text='Tamaño recomendado de la imagen 200px X 200px pixeles', label='Imagen', required=True)), ('alt_text', wagtail.core.blocks.TextBlock(blank=False, help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', label='Texto alternativo', required=False))]))], blank=True, verbose_name='Portafolio, políticas y protocolos de servicio'),
        ),
        migrations.AddField(
            model_name='serviciociudanopage',
            name='channel_list',
            field=wagtail.core.fields.StreamField([('Canales', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Titulo del canal de atención', label='Titulo del canal de atención', required=True)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono del canal de atención, solo imágenes en formato SVG.', label='Icono del canal de atención', required=True)), ('description', wagtail.core.blocks.CharBlock(help_text='Descripción general del canal de atención', label='Descripción del canal de atención', required=True)), ('enlaces', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(blank=False, help_text='Subitems del canal de atención principal', label='Subitem', required=True))], closed=False, icon='link', value_class=apps.servicio_ciudadano.blocks.LinkStructValue), required=True))]))], blank=True, verbose_name='Canales de atención'),
        ),
        migrations.AddField(
            model_name='serviciociudanopage',
            name='intro',
            field=models.CharField(blank=True, help_text='Introducción de la sección', max_length=254, null=True, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='serviciociudanopage',
            name='intro_title',
            field=models.CharField(default='Servicio al ciudadano', max_length=254, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='serviciociudanopage',
            name='participation_list',
            field=wagtail.core.fields.StreamField([('Mencanismos', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Titulo del mecanismo de participación', label='Titulo', required=True)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono del mecanismo de participación, solo imágenes en formato SVG.', label='Icono', required=True)), ('description', wagtail.core.blocks.CharBlock(help_text='Descripción del mecanismo de participación', label='Descripción del elemento', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local', label='Link a página externa:', required=False))]))], blank=True, verbose_name='Mecanismos de participación'),
        ),
        migrations.AddField(
            model_name='serviciociudanopage',
            name='services_list',
            field=wagtail.core.fields.StreamField([('Servicios', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Titulo del servicio', label='Titulo', required=True)), ('description', wagtail.core.blocks.CharBlock(help_text='Descripción del mecanismo de participación', label='Descripción del servicio', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local', label='Link a página externa:', required=False))]))], blank=True, verbose_name='Servicios'),
        ),
        migrations.AddField(
            model_name='serviciociudanopage',
            name='slider',
            field=wagtail.core.fields.StreamField([('slider', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(blank=False, help_text='Tamaño recomendado de la imagen 1820px X 680px pixeles', label='Imagen', required=True)), ('video', wagtail.core.blocks.URLBlock(blank=False, help_text='Si completa este campo, la imagen no será presentada. El link requerido debe tener el siguiente formato https://www.youtube.com/embed/lkizzbz2ci85', label='Link a página externa', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(blank=False, help_text='Complete este campo si desea enlazar este slider con una página local', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(blank=False, help_text='Complete este campo si desea enlazar este slider con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local', label='Link a página externa', required=False)), ('alt_text', wagtail.core.blocks.TextBlock(blank=False, help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', label='Texto alternativo', required=False))]))], blank=True, verbose_name='Slider'),
        ),
    ]
