# Generated by Django 3.1.13 on 2021-09-05 20:18

import apps.servicio_ciudadano.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_ciudadano', '0006_auto_20210905_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciociudanopage',
            name='channel_list',
            field=wagtail.core.fields.StreamField([('Canales', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Titulo del canal de atención', label='Titulo del canal de atención', required=True)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono del canal de atención, solo imágenes en formato SVG.', label='Icono del canal de atención', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Descripción general del canal de atención', label='Descripción del canal de atención', required=True)), ('subitems', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(blank=False, help_text='Subitems del canal de atención principal', label='Subitem', required=True))], closed=False, icon='link', value_class=apps.servicio_ciudadano.blocks.LinkStructValue), required=True))]))], blank=True, verbose_name='Canales de atención'),
        ),
    ]
