# Generated by Django 3.1.13 on 2021-09-05 20:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_ciudadano', '0007_auto_20210905_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciociudanopage',
            name='participation_list',
            field=wagtail.core.fields.StreamField([('Mencanismos', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Titulo del mecanismo de participación', label='Titulo', required=True)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono del mecanismo de participación, solo imágenes en formato SVG.', label='Icono', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Descripción del mecanismo de participación', label='Descripción del elemento', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local', label='Link a página externa', required=False))]))], blank=True, verbose_name='Mecanismos de participación'),
        ),
        migrations.AlterField(
            model_name='serviciociudanopage',
            name='services_list',
            field=wagtail.core.fields.StreamField([('Servicios', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Titulo del servicio', label='Titulo', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Descripción del mecanismo de participación', label='Descripción del servicio', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local', label='Link a página externa', required=False))]))], blank=True, verbose_name='Servicios'),
        ),
    ]
