# Generated by Django 3.1.13 on 2021-09-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_ciudadano', '0008_auto_20210905_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciociudanopage',
            name='briefcase_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='serviciociudanopage',
            name='channel_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='serviciociudanopage',
            name='participation_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='serviciociudanopage',
            name='services_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
    ]
