# Generated by Django 3.1.13 on 2021-09-10 16:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('servicio_ciudadano', '0028_auto_20210910_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='forosindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Imagen que representa la sección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='forosindexpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='forosindexpage',
            name='intro_title',
            field=models.CharField(default='Participa', max_length=254, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='forosindexpage',
            name='link_video',
            field=models.URLField(blank=True, help_text='Si completa este campo, la imagen no será presentada. El link requerido debe tener el siguiente formato https://www.youtube.com/embed/lkizzbz2ci85', verbose_name='Video'),
        ),
    ]
