# Generated by Django 3.1.13 on 2021-09-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_ciudadano', '0029_auto_20210910_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forosindexpage',
            name='intro_title',
            field=models.CharField(default='Foros', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
