# Generated by Django 3.1.13 on 2021-11-06 22:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('servicio_ciudadano', '0042_auto_20211106_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRetentionTablePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('table_title', models.CharField(default='Rendición de cuentas', max_length=254, verbose_name='Título de la sección')),
                ('table', wagtail.core.fields.StreamField([('Elementos', wagtail.core.blocks.StructBlock([('section_code', wagtail.core.blocks.CharBlock(help_text='Código Sección', label='Código Sección', required=False)), ('section', wagtail.core.blocks.TextBlock(help_text='Sección', label='Sección ', required=False)), ('sub_section_code', wagtail.core.blocks.CharBlock(help_text='Código Subsección', label='Código Subsección', required=False)), ('subsection_description', wagtail.core.blocks.TextBlock(help_text='Subsección', label='Subsección', required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(help_text='Seleccione un documento', label='Documento', required=True)), ('starred', wagtail.core.blocks.ChoiceBlock(choices=[('true', 'Destacado')], help_text='Seleccione Destacado si el archivo debe resaltarse en la lista de elementos', label='Item destacado', required=False))]))], blank=True, verbose_name='Codificación Estructura Organizacional')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
