# Generated by Django 3.1.13 on 2021-11-06 22:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('servicio_ciudadano', '0043_documentretentiontablepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentRetentionTablePage',
            new_name='TablaRetencionDocumentalPage',
        ),
    ]
