# Generated by Django 3.1.13 on 2021-11-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_ciudadano', '0044_auto_20211106_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaretenciondocumentalpage',
            name='table_title',
            field=models.CharField(default='Codificación Estructura Organizacional del Ministerio de Minas y Energía', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
