# Generated by Django 3.1.13 on 2021-11-14 17:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('servicio_ciudadano', '0048_auto_20211106_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='alt_text',
            field=models.TextField(blank=True, help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', verbose_name='Texto alternativo'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='control_intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Bloque Dos', null=True, verbose_name='Bloque Dos'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='control_title',
            field=models.CharField(default='Rendición de Cuentas', max_length=254, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='current_alt_text',
            field=models.TextField(blank=True, help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', verbose_name='Texto alternativo'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='current_image',
            field=models.ForeignKey(blank=True, help_text='Imagen que representa la sección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='current_intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='current_title',
            field=models.CharField(default='Rendición de Cuentas', max_length=254, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='document_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='general_block_one',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Bloque Uno', null=True, verbose_name='Bloque Uno'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='general_block_two',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Bloque Dos', null=True, verbose_name='Bloque Dos'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='general_title',
            field=models.CharField(default='Rendición de Cuentas', max_length=254, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='general_video',
            field=models.URLField(blank=True, help_text='Si completa este campo, la imagen no será presentada. El link requerido debe tener el siguiente formato https://www.youtube.com/embed/lkizzbz2ci85', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='historical_list',
            field=wagtail.core.fields.StreamField([('Lista', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento (Opcional)', label='Título', required=False)), ('subitems', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True))]), blank=True, help_text='Lista de elementos', label='Lista de elementos', required=False))]))], blank=True, verbose_name='Histórico Rendición de cuentas'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='questions_list',
            field=wagtail.core.fields.StreamField([('Preguntas', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del portafolio, políticas y/o protocolos de servicio ', label='Título', required=True)), ('main_description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True))]))], blank=True, verbose_name='Preguntas'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='questions_title',
            field=models.CharField(default='Rendición de Cuentas', max_length=254, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='rendicioncuentaspage',
            name='tab_intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='rendicioncuentaspage',
            name='plans_list',
            field=wagtail.core.fields.StreamField([('Tabs', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Descripción del elemento', icon='fa-paragraph', label='Descripción', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local', label='Link a página externa', required=False))]))], blank=True, verbose_name='Pestañas'),
        ),
    ]
