# Generated by Django 3.1.13 on 2021-11-14 18:13

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('servicio_ciudadano', '0049_auto_20211114_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendicioncuentaspage',
            name='control_title',
            field=models.CharField(default='Control Social', max_length=254, verbose_name='Título de la sección'),
        ),
        migrations.AlterField(
            model_name='rendicioncuentaspage',
            name='questions_list',
            field=wagtail.core.fields.StreamField([('Preguntas', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('main_description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True))]))], blank=True, verbose_name='Preguntas'),
        ),
        migrations.AlterField(
            model_name='rendicioncuentaspage',
            name='questions_title',
            field=models.CharField(default='Preguntas y respuestas', max_length=254, verbose_name='Título de la sección'),
        ),
        migrations.CreateModel(
            name='MecanismosProteccionDerechosCiudadanosPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(default='Rendición de cuentas', max_length=254, verbose_name='Título de la sección')),
                ('intro', wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción')),
                ('link_video', models.URLField(blank=True, help_text='Si completa este campo, la imagen no será presentada. El link requerido debe tener el siguiente formato https://www.youtube.com/embed/lkizzbz2ci85', verbose_name='Video')),
                ('alt_text', models.TextField(blank=True, help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', verbose_name='Texto alternativo')),
                ('request_title', models.CharField(default='Peticiones, Quejas, Reclamos y Denuncias - PQRD', max_length=254, verbose_name='Título de la sección')),
                ('request_intro', wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción')),
                ('request_list', wagtail.core.fields.StreamField([('Mecanismos', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('main_description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True))]))], blank=True, verbose_name='Otros Mecanismos')),
                ('others_title', models.CharField(default='Otros mecanismos constitucionales para la protección de los derechos ciudadanos', max_length=254, verbose_name='Título de la sección')),
                ('others_list', wagtail.core.fields.StreamField([('Tabs', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Descripción del elemento', icon='fa-paragraph', label='Descripción', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local', label='Link a página externa', required=False))]))], blank=True, verbose_name='Pestañas')),
                ('mechanisms_title', models.CharField(default='Mecanismos de participación', max_length=254, verbose_name='Título de la sección')),
                ('mechanisms_list', wagtail.core.fields.StreamField([('Mecanismos', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('main_description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True))]))], blank=True, verbose_name='Mecanismos de participación')),
                ('control_title', models.CharField(default='Mecanismos de Control Ciudadano para la Vigilancia de la Gestión Pública', max_length=254, verbose_name='Título de la sección')),
                ('control_intro', wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción')),
                ('control_list', wagtail.core.fields.StreamField([('Tabs', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Descripción del elemento', icon='fa-paragraph', label='Descripción', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local', label='Link a página externa', required=False))]))], blank=True, verbose_name='Pestañas')),
                ('spaces_title', models.CharField(default='Espacios para la Intervención de las Veedurías Ciudadanas en el Control Social de la Gestión del Ministerio de Minas y Energía', max_length=254, verbose_name='Título de la sección')),
                ('spaces_intro', wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción')),
                ('spaces_block_one', wagtail.core.fields.RichTextField(blank=True, help_text='Bloque Uno', null=True, verbose_name='Bloque Uno')),
                ('spaces_block_two', wagtail.core.fields.RichTextField(blank=True, help_text='Bloque Dos', null=True, verbose_name='Bloque Dos')),
                ('spaces_block_three', wagtail.core.fields.RichTextField(blank=True, help_text='Bloque tres', null=True, verbose_name='Bloque tres')),
                ('spaces_block_four', wagtail.core.fields.RichTextField(blank=True, help_text='Bloque Cuatro', null=True, verbose_name='Bloque Cuatro')),
                ('minister_title', models.CharField(default='El Ministerio de Minas y Energía en su compromiso con la ciudadanía declara', max_length=254, verbose_name='Título de la sección')),
                ('minister_intro', wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción')),
                ('image', models.ForeignKey(blank=True, help_text='Imagen que representa la sección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
