# Generated by Django 3.1.13 on 2021-11-14 20:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_ciudadano', '0050_auto_20211114_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanismosproteccionderechosciudadanospage',
            name='request_list',
            field=wagtail.core.fields.StreamField([('Elementos', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('main_description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True))]))], blank=True, verbose_name='Elemento'),
        ),
    ]
