# Generated by Django 3.1.13 on 2021-11-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_ciudadano', '0052_auto_20211114_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informemecanismosparticipacionpage',
            name='intro_title',
            field=models.CharField(default='Informe de mecanismos de participación', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
