# Generated by Django 3.1.13 on 2021-11-14 21:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('servicio_ciudadano', '0053_auto_20211114_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosEspaciosCiudadanosPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('element_list', wagtail.core.fields.StreamField([('Lista', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Nombre del elemento', label='Nombre', required=True)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono, solo imágenes en formato SVG.', label='Icono', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Descripción del elemento', icon='fa-paragraph', label='Descripción', required=True))]))], blank=True, verbose_name='Eventos y Espacios Ciudadanos')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
