# Generated by Django 3.1.13 on 2021-11-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_ciudadano', '0055_eventosespaciosciudadanospage_second_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosespaciosciudadanospage',
            name='second_links_title',
            field=models.CharField(default='Registre y consulte su PQRS', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
