# Generated by Django 3.1.13 on 2021-12-16 23:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('servicio_ciudadano', '0059_acordeonpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventosEspaciosCiudadanosPage',
            new_name='PqrsPage',
        ),
    ]
