# Generated by Django 3.1.13 on 2022-03-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_ciudadano', '0062_auto_20220331_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planparticipacionciudadanapage',
            name='assigned_tabs_list_title',
        ),
        migrations.RemoveField(
            model_name='planparticipacionciudadanapage',
            name='general_tabs_list',
        ),
    ]
