# Generated by Django 3.1.7 on 2021-05-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('transparencia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='participaPage',
        ),
    ]
