# Generated by Django 3.1.7 on 2021-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0004_auto_20210606_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparenciapage',
            name='intro_title',
            field=models.CharField(default='Transparencia', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
