# Generated by Django 3.1.13 on 2021-09-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0007_auto_20210907_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transparenciapage',
            name='intro',
            field=models.TextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
    ]
