# Generated by Django 3.1.13 on 2021-09-30 01:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0011_auto_20210928_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transparenciapage',
            name='second_links',
            field=wagtail.core.fields.StreamField([('Enlaces', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(help_text='Texto del link que será mostrado al público', label='Texto del link', max_length=20, required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono del link, solo se acepta imágenes en formato SVG.', label='Icono del elemento', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local.', label='Link a página local:', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa.Si este campo está completo, no se tendrá en cuenta el link a página local.', label='Link a página externa:', required=False))]))], blank=True, verbose_name='Enlaces secundarios'),
        ),
    ]
