# Generated by Django 3.1.13 on 2021-10-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparencia', '0013_declaracionrentapage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracionrentapage',
            name='intro_title',
            field=models.CharField(default='Publicación de la declaración de renta y complementarios de funcionarios públicos', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
