# Generated by Django 3.1.7 on 2021-05-12 15:40

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_affiliatedentitiesblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedEntitiesBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_company', wagtail.core.fields.StreamField([('Entidad_Vinculada', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Texto que será mostrado al público.', label='Nombre de la entidad', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen de la entidad', label='Imagen', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local.', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local.', label='Link a página externa', required=False)), ('description', wagtail.core.blocks.TextBlock(help_text=None, label='Descripción de la empresa', required=True))]))], blank=True, verbose_name='Entidad Vinculadas')),
            ],
            options={
                'verbose_name_plural': 'Entidades Vinculadas',
            },
        ),
        migrations.AlterField(
            model_name='affiliatedentitiesblock',
            name='sector_company',
            field=wagtail.core.fields.StreamField([('Entidad_Adscrita', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Texto que será mostrado al público.', label='Nombre de la entidad', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen de la entidad', label='Imagen', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local.', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local.', label='Link a página externa', required=False)), ('description', wagtail.core.blocks.TextBlock(help_text=None, label='Descripción de la empresa', required=True))]))], blank=True, verbose_name='Entidad Adscrita'),
        ),
        migrations.AlterField(
            model_name='footerblock',
            name='social_networks',
            field=wagtail.core.fields.StreamField([('Redes_Sociales', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Texto del link que será mostrado al público.', label='Texto del link:', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Texto del link que será mostrado al público.', label='Imagen:', required=True)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Enlace hacia la página.', label='Link a página externa:', required=True))]))], blank=True, verbose_name='Redes Sociales'),
        ),
        migrations.AlterField(
            model_name='headerblock',
            name='links',
            field=wagtail.core.fields.StreamField([('enlaces', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(blank=False, help_text='Texto del link que será mostrado al público.', label='Texto del link:', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local.', label='Link a página local:', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local.', label='Link a página externa:', required=False))]))], blank=True, verbose_name='Enlaces de gobierno'),
        ),
    ]
