# Generated by Django 3.1.10 on 2021-07-13 18:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20210528_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatedentitiesblock',
            name='sector_company',
            field=wagtail.core.fields.StreamField([('Entidad_Adscrita', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Texto que será mostrado al público.', label='Nombre de la entidad', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen de la entidad', label='Imagen', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local.', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local.', label='Link a página externa', required=False)), ('description', wagtail.core.blocks.TextBlock(help_text=None, label='Descripción de la empresa', required=True))]))], blank=True, verbose_name='Entidad Adscrita'),
        ),
        migrations.AlterField(
            model_name='footerblock',
            name='contact_info',
            field=wagtail.core.fields.RichTextField(help_text='Información de contacto', verbose_name='Información de contacto'),
        ),
        migrations.AlterField(
            model_name='footerblock',
            name='general_info',
            field=wagtail.core.fields.RichTextField(help_text='Información de la institución', verbose_name='Información General'),
        ),
        migrations.AlterField(
            model_name='footerblock',
            name='social_networks',
            field=wagtail.core.fields.StreamField([('Redes_Sociales', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Texto del link que será mostrado al público.', label='Texto del link:', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Texto del link que será mostrado al público.', label='Imagen:', required=True)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Enlace hacia la página.', label='Link a página externa:', required=True))]))], blank=True, verbose_name='Redes Sociales'),
        ),
        migrations.AlterField(
            model_name='headerblock',
            name='links',
            field=wagtail.core.fields.StreamField([('enlaces', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(blank=False, help_text='Texto del link que será mostrado al público.', label='Texto del link:', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local.', label='Link a página local:', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local.', label='Link a página externa:', required=False))]))], blank=True, verbose_name='Enlaces de gobierno'),
        ),
        migrations.AlterField(
            model_name='relatedentitiesblock',
            name='sector_company',
            field=wagtail.core.fields.StreamField([('Entidad_Vinculada', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Texto que será mostrado al público.', label='Nombre de la empresa', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen de la empresa', label='Imagen', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local.', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local.', label='Link a página externa', required=False)), ('represent', wagtail.core.blocks.CharBlock(help_text='Digite el nombre completo del representante legal', label='Nombre del representante legal de la empresa', required=True)), ('mail', wagtail.core.blocks.EmailBlock(help_text='Digite el correo corporativo', label='Correo Corporativo', required=True))]))], blank=True, verbose_name='Entidad Vinculadas'),
        ),
    ]
