# Generated by Django 3.1.10 on 2021-07-23 15:58

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20210713_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoEntitiesBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inf_entity', wagtail.core.fields.StreamField([('Sistema_Informacion', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Texto que será mostrado al público.', label='Nombre de la entidad', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen de la entidad', label='Imagen', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local.', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local.', label='Link a página externa', required=False)), ('description', wagtail.core.blocks.TextBlock(help_text=None, label='Descripción de la empresa', required=True))]))], blank=True, verbose_name='Define los sistemas de informacion')),
            ],
            options={
                'verbose_name_plural': 'Sistemas de Información',
            },
        ),
    ]
