# Generated by Django 3.1.13 on 2021-11-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20211125_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ano',
            new_name='Year',
        ),
    ]
