# Generated by Django 3.1.13 on 2021-11-25 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('repositorio_normativo', '0002_auto_20211125_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptopage',
            name='document_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Anexos'),
        ),
    ]
