# Generated by Django 3.1.13 on 2021-11-25 19:31

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('repositorio_normativo', '0003_auto_20211125_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptopage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(help_text='A comma-separated list of tags.', through='repositorio_normativo.ConceptoPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
