# Generated by Django 3.1.13 on 2022-02-24 04:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio_normativo', '0007_auto_20220223_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendanormativapage',
            name='menu_list',
            field=wagtail.core.fields.StreamField([('Items', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('main_description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True))]))], blank=True, verbose_name='Proyectos Normativos para Consulta a la Ciudadanía'),
        ),
    ]
