# Generated by Django 3.1.13 on 2022-02-27 04:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('repositorio_normativo', '0013_remove_edictospage_tab_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstructuraOrganizacionalGrupoRegaliasPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción')),
                ('table_title', models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección')),
                ('table_estructura', wagtail.core.fields.StreamField([('Elementos', wagtail.core.blocks.StructBlock([('subitems', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Nombre y apellido', label='Nombre', required=True)), ('email', wagtail.core.blocks.CharBlock(help_text='Correo', label='Correo', required=True)), ('phone', wagtail.core.blocks.CharBlock(help_text='Celular', label='Celular', required=True))]), blank=True, help_text='Lista de elementos', label='Lista de elementos', required=False))]))], blank=True, verbose_name='Grupo de ejecución estratégica del sector extractivo')),
                ('image', models.ForeignKey(blank=True, help_text='Imagen que representa la sección.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
