# Generated by Django 3.1.13 on 2022-02-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('repositorio_normativo', '0015_inversionessgrcovid19page'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendanormativapage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Imagen que representa la sección.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen'),
        ),
    ]
