# Generated by Django 3.1.13 on 2022-03-01 19:57

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio_normativo', '0017_agendanormativapage_items_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendanormativapage',
            name='data_description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Descripcion agenda normativa', null=True, verbose_name='Descripcion agenda normativa'),
        ),
    ]
