# Generated by Django 3.1.13 on 2022-03-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio_normativo', '0018_agendanormativapage_data_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendanormativapage',
            name='title_list_one',
            field=models.CharField(default='Proyectos Normativos para Consulta a la Ciudadanía', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
