# Generated by Django 3.1.13 on 2022-03-01 20:29

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio_normativo', '0019_auto_20220301_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendanormativapage',
            name='data_description_acordeon',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Descripcion Proyectos Normativos', null=True, verbose_name='Descripcion Proyectos Normativos'),
        ),
    ]
