# Generated by Django 3.1.13 on 2022-03-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio_normativo', '0020_agendanormativapage_data_description_acordeon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendanormativapage',
            name='data_description_acordeon',
        ),
    ]
