# Generated by Django 3.1.13 on 2022-03-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio_normativo', '0023_auto_20220301_1720'),
        ('repositorio_normativo', '0020_noticiosoadministrativopage'),
    ]

    operations = [
    ]
