# Generated by Django 3.1.13 on 2022-03-03 22:48

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio_normativo', '0025_auto_20220303_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionesadministrativaspage',
            name='edics_intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='notificacionesadministrativaspage',
            name='edics_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
    ]
