# Generated by Django 3.1.13 on 2022-03-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio_normativo', '0029_remove_edictospage_menu_list_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edictospage',
            old_name='retie_list_title',
            new_name='menu_list_title',
        ),
    ]
