# Generated by Django 3.1.13 on 2022-03-09 04:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio_normativo', '0030_auto_20220309_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiosoadministrativopage',
            name='notiadmin_list_title',
        ),
        migrations.AddField(
            model_name='noticiosoadministrativopage',
            name='noti_intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
    ]
