# Generated by Django 3.1.13 on 2022-03-09 04:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio_normativo', '0034_auto_20220309_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edictospage',
            name='retie_list',
        ),
        migrations.AddField(
            model_name='edictospage',
            name='edict_list',
            field=wagtail.core.fields.StreamField([('Items', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(help_text='Seleccione un documento', label='Documento', required=False)), ('intro_1', wagtail.core.blocks.RichTextBlock(help_text='Texto descriptivo', icon='fa-paragraph', label='No. Proceso o fecha de publicación', required=False, template='blocks/paragraph_block.html')), ('intro_2', wagtail.core.blocks.RichTextBlock(help_text='Texto descriptivo', icon='fa-paragraph', label='Nombre del Interesado', required=False, template='blocks/paragraph_block.html')), ('intro_3', wagtail.core.blocks.RichTextBlock(help_text='Texto descriptivo', icon='fa-paragraph', label='Sección', required=False, template='blocks/paragraph_block.html')), ('intro_4', wagtail.core.blocks.RichTextBlock(help_text='Texto descriptivo', icon='fa-paragraph', label='Acto Administrativo', required=False, template='blocks/paragraph_block.html')), ('intro_5', wagtail.core.blocks.RichTextBlock(help_text='Texto descriptivo', icon='fa-paragraph', label='Fecha de emisión', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Lista Enlaces '),
        ),
        migrations.AlterField(
            model_name='noticiosoadministrativopage',
            name='notiadmin_list',
            field=wagtail.core.fields.StreamField([('Items', wagtail.core.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(help_text='Seleccione un documento', label='Documento', required=False)), ('intro_1', wagtail.core.blocks.RichTextBlock(help_text='Texto descriptivo', icon='fa-paragraph', label='Fecha de publicación', required=False, template='blocks/paragraph_block.html')), ('intro_2', wagtail.core.blocks.RichTextBlock(help_text='Texto descriptivo', icon='fa-paragraph', label='Nombre del Interesado', required=False, template='blocks/paragraph_block.html')), ('intro_3', wagtail.core.blocks.RichTextBlock(help_text='Texto descriptivo', icon='fa-paragraph', label='Procesos y/o Trámites', required=False, template='blocks/paragraph_block.html')), ('intro_4', wagtail.core.blocks.RichTextBlock(help_text='Texto descriptivo', icon='fa-paragraph', label='Acto Administrativo', required=False, template='blocks/paragraph_block.html')), ('intro_5', wagtail.core.blocks.RichTextBlock(help_text='Texto descriptivo', icon='fa-paragraph', label='Fecha Acto Administrativo', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Lista Enlaces'),
        ),
    ]
