# Generated by Django 3.1.13 on 2022-03-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio_normativo', '0044_acuerdosconciliatoriospage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdosconciliatoriospage',
            name='intro_title',
            field=models.CharField(default='Título de la sección', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
