# Generated by Django 3.1.13 on 2022-03-30 05:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('repositorio_normativo', '0053_auto_20220324_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorionormativopage',
            name='book_one',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='repositorionormativopage',
            name='book_one_description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Libro 1', null=True, verbose_name='Libro 1'),
        ),
        migrations.AddField(
            model_name='repositorionormativopage',
            name='book_three',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='repositorionormativopage',
            name='book_three_description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Libro 3', null=True, verbose_name='Libro 3'),
        ),
        migrations.AddField(
            model_name='repositorionormativopage',
            name='decreto_description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Decreto Número', null=True, verbose_name='Decreto Número'),
        ),
        migrations.AddField(
            model_name='repositorionormativopage',
            name='decreto_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
        migrations.AddField(
            model_name='repositorionormativopage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Imagen que representa la sección.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='repositorionormativopage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='repositorionormativopage',
            name='intro_tab',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='repositorionormativopage',
            name='tab_list',
            field=wagtail.core.fields.StreamField([('Tabs', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Descripción del elemento', icon='fa-paragraph', label='Descripción', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa. Si este campo está completo, no se tendrá en cuenta el link a página local', label='Link a página externa', required=False))]))], blank=True, verbose_name='Pestañas'),
        ),
        migrations.AddField(
            model_name='repositorionormativopage',
            name='tab_list_title',
            field=models.CharField(blank=True, help_text='Título que será presentado al publico', max_length=255, null=True, verbose_name='Título de la sección'),
        ),
    ]
