# Generated by Django 3.1.2 on 2021-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participa', '0002_auto_20210605_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participapage',
            name='link_video',
            field=models.URLField(blank=True, help_text='Si completa este campo, la imagen no será presentada. El link requerido debe tener el siguiente formato https://www.youtube.com/embed/lkizzbz2ci85', verbose_name='Video'),
        ),
    ]
