# Generated by Django 3.1.7 on 2021-06-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participa', '0003_auto_20210622_1738'),
        ('participa', '0003_auto_20210622_0920'),
    ]

    operations = [
    ]
