# Generated by Django 3.1.7 on 2021-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participa', '0004_merge_20210623_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='participapage',
            name='intro_title',
            field=models.CharField(default='Transparencia', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
