# Generated by Django 3.1.7 on 2021-07-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participa', '0005_participapage_intro_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participapage',
            name='intro_title',
            field=models.CharField(default='Participa', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
