# Generated by Django 3.1.13 on 2021-09-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participa', '0010_auto_20210908_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='participapage',
            name='alt_text',
            field=models.TextField(blank=True, help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', verbose_name='Texto alternativo'),
        ),
    ]
