# Generated by Django 3.1.7 on 2021-04-12 17:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('ministerio', '0005_estrategicopage_gestionpage_organigramainteractivopage_planesprogramaspage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntesControlExternoPage',
            new_name='ContratacionPresupuestoPage',
        ),
        migrations.RemoveField(
            model_name='incentivoproduccionpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='ministropage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='ministrosentidadpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='planeacionpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='presupuestopage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='talentohumanopage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='transparenciaministeriopage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='viceministrospage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ContratacionPage',
        ),
        migrations.DeleteModel(
            name='IncentivoProduccionPage',
        ),
        migrations.DeleteModel(
            name='MinistroPage',
        ),
        migrations.DeleteModel(
            name='MinistrosEntidadPage',
        ),
        migrations.DeleteModel(
            name='PlaneacionPage',
        ),
        migrations.DeleteModel(
            name='PresupuestoPage',
        ),
        migrations.DeleteModel(
            name='TalentoHumanoPage',
        ),
        migrations.DeleteModel(
            name='TransparenciaMinisterioPage',
        ),
        migrations.DeleteModel(
            name='ViceministrosPage',
        ),
    ]
