# Generated by Django 3.1.7 on 2021-04-13 14:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0006_auto_20210412_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturacorporativapage',
            name='slider',
            field=wagtail.core.fields.StreamField([('Cultura_Corporativa', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen que representa el elemento de cultura corporativa.', label='Imagen', required=True)), ('name', wagtail.core.blocks.CharBlock(help_text='Título que describe el elemento de cultura corporativa.', label='Título del Elemento', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla).', label='Texto alternativo:', required=False)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'hr'], help_text='Texto descriptivo del elemento de cultura corporativa.', icon='fa-paragraph', label='Descripción:', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Cultura Corporativa'),
        ),
    ]
