# Generated by Django 3.1.7 on 2021-04-21 19:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0009_auto_20210414_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiapage',
            name='time_period',
            field=wagtail.core.fields.StreamField([('Periodo', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Corresponde al periodo de tiempo que se presentara como título de la sección. Ejemplo: ‘Ministros de Minas y Energía entre 2010 – 2020’', label='Periodo de tiempo', required=True)), ('ministros', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(blank=False, label='Nombre', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=False, label='Foto de perfil', required=True)), ('alt_text', wagtail.core.blocks.TextBlock(help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla).', label='Texto alternativo foto de perfil', required=False)), ('period', wagtail.core.blocks.TextBlock(blank=False, help_text='Periodo de tiempo en el cual estuvo activo el funcionario. Ejemplo: ‘7 de agosto de 2018 al 1 junio de 2020’', label='Peridodo', required=True)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'hr'], help_text='Breve descripción del funcionario.', icon='fa-paragraph', label='Descripción:', required=False, template='blocks/paragraph_block.html'))], closed=True, icon='user')))]))], blank=True, verbose_name='Ministros de la entidad'),
        ),
        migrations.AlterField(
            model_name='culturacorporativapage',
            name='corporate_culture',
            field=wagtail.core.fields.StreamField([('Cultura_Corporativa', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Título que describe el elemento de cultura corporativa.', label='Título del Elemento', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen que representa el elemento de cultura corporativa.', label='Imagen', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla).', label='Texto alternativo', required=False)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ul', 'ol', 'italic', 'link', 'hr'], help_text='Texto descriptivo del elemento de cultura corporativa.', icon='fa-paragraph', label='Descripción', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Cultura Corporativa'),
        ),
    ]
