# Generated by Django 3.1.7 on 2021-04-22 13:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0011_auto_20210422_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiapage',
            name='history',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Historia', null=True),
        ),
    ]
