# Generated by Django 3.1.7 on 2021-04-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0002_svg_edit_code'),
        ('ministerio', '0014_estructurasectorpage_sector_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='estructurasectorpage',
            name='sector_entities_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg'),
        ),
        migrations.AddField(
            model_name='estructurasectorpage',
            name='sector_entities_title',
            field=models.CharField(help_text='Título del componente', max_length=255, null=True),
        ),
    ]
