# Generated by Django 3.1.7 on 2021-05-06 22:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0016_auto_20210423_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlinternopage',
            name='acordeon',
            field=wagtail.core.fields.StreamField([('Acordeon', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Titulo del elemento.', label='Titulo del elemento', required=True)), ('description', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'hr'], help_text='Texto descriptivo.', icon='fa-paragraph', label='Descripción', required=True))]))], blank=True, verbose_name='Acordeon'),
        ),
        migrations.AddField(
            model_name='controlinternopage',
            name='element',
            field=wagtail.core.fields.StreamField([('Elemento', wagtail.core.blocks.StructBlock([('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono de la parte superior izquierda del elemento, solo se acepta imágenes en formato SVG.', label='Icono del elemento', required=True)), ('name', wagtail.core.blocks.CharBlock(help_text='Titulo del elemento.', label='Titulo del elemento', required=True)), ('description', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'hr'], help_text='Texto descriptivo.', icon='fa-paragraph', label='Descripción', required=True)), ('background_color', wagtail.core.blocks.CharBlock(help_text='Color de fondo para el elemento en formato hexadecimal. Ejemplo: #5A0C6D', label='Color de fondo', max_length=7, required=True)), ('text_color', wagtail.core.blocks.CharBlock(help_text='Color de texto en formato hexadecimal. Ejemplo: #5A0C6D', label='Color de texto', max_length=7, required=True))]))], blank=True, verbose_name='Elementos'),
        ),
        migrations.AddField(
            model_name='controlinternopage',
            name='intro_subseccions',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='controlinternopage',
            name='subsections',
            field=wagtail.core.fields.StreamField([('Subseccion', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Titulo de la subsección.', label='Titulo de la subsección', required=True)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono de la subsección, solo se acepta imágenes en formato SVG.', label='Icono de la subsección', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local.', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa.Si este campo está completo, no se tendrá en cuenta el link a página local.', label='Link a página externa:', required=False))]))], blank=True, verbose_name='Elementos'),
        ),
        migrations.AlterField(
            model_name='historiapage',
            name='history',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Historia', null=True, verbose_name='Historia'),
        ),
        migrations.AlterField(
            model_name='historiapage',
            name='video_description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Descripción del video', null=True, verbose_name='Descripción del video'),
        ),
    ]
