# Generated by Django 3.1.7 on 2021-05-07 20:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0020_auto_20210507_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiapage',
            name='current_minister',
            field=wagtail.core.fields.StreamField([('Ministro', wagtail.core.blocks.StructBlock([('Nombre', wagtail.core.blocks.CharBlock(blank=False, label='Nombre', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=False, label='Foto de perfil', required=True)), ('alt_text', wagtail.core.blocks.TextBlock(blank=False, help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla).', label='Texto alternativo foto de perfil', required=False)), ('period', wagtail.core.blocks.TextBlock(blank=False, help_text='Periodo de tiempo en el cual estuvo activo el funcionario. Ejemplo: ‘7 de agosto de 2018 al 1 junio de 2020’', label='Peridodo', required=True)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'hr'], help_text='Breve descripción del funcionario.', icon='fa-paragraph', label='Descripción:', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Ministros actual'),
        ),
    ]
