# Generated by Django 3.1.7 on 2021-05-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0021_historiapage_current_minister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiapage',
            name='current_minister',
        ),
    ]
