# Generated by Django 3.1.2 on 2021-05-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0017_auto_20210512_1750'),
        ('ministerio', '0022_remove_historiapage_current_minister'),
    ]

    operations = [
    ]
