# Generated by Django 3.1.2 on 2021-06-22 14:20

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0023_merge_20210512_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturacorporativapage',
            name='corporate_culture_objetives',
            field=wagtail.core.fields.StreamField([('Objetivos_de_Calidad', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Título que describe el elemento de objetivos de calidad.', label='Título del Elemento', required=True)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ul', 'ol', 'italic', 'link', 'hr'], help_text='Texto descriptivo del elemento de objetivos de calidad.', icon='fa-paragraph', label='Descripción', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Objetivos de Calidad'),
        ),
    ]
