# Generated by Django 3.1.7 on 2021-06-29 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('ministerio', '0025_auto_20210629_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariopage',
            name='position',
            field=models.CharField(blank=True, help_text='Cargo del funcionario.', max_length=255, verbose_name='Cargo del componente'),
        ),
        migrations.AlterField(
            model_name='funcionariopage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Imagen de perfil del funcionario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen de perfil del funcionario'),
        ),
        migrations.AlterField(
            model_name='funcionariopage',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre del funcionario.', max_length=255, verbose_name='Nombre del funcionario'),
        ),
    ]
