# Generated by Django 3.1.7 on 2021-06-29 20:20

import apps.ministerio.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0029_funcionariopage_staff_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariopage',
            name='staff_list',
            field=wagtail.core.fields.StreamField([('Personal', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Titulo del elemento.', label='Nombre del funcionario', required=True)), ('position', wagtail.core.blocks.CharBlock(help_text='Titulo del elemento.', label='Cargo del funcionario', required=True)), ('personal', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('group', wagtail.core.blocks.CharBlock(blank=False, help_text='Nombre del grupo.', label='Nombre del grupo', required=False)), ('name', wagtail.core.blocks.CharBlock(blank=False, help_text='Nombre del funcionario a cargo del grupo.', label='Nombre del funcionario', required=False))], closed=False, icon='user', value_class=apps.ministerio.blocks.LinkStructValue), required=True))]))], blank=True, verbose_name='Grupos y Personas'),
        ),
    ]
