# Generated by Django 3.1.7 on 2021-06-29 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('ministerio', '0030_auto_20210629_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='despacho_viceministro_minas',
            field=models.ForeignKey(blank=True, help_text='Seleccione el funcionario correspondiente para este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Despacho Viceministro de Minas'),
        ),
    ]
