# Generated by Django 3.1.7 on 2021-06-29 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('ministerio', '0031_organigramainteractivopage_despacho_viceministro_minas'),
    ]

    operations = [
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='despacho_ministerio_minas_energía',
            field=models.ForeignKey(blank=True, help_text='Seleccione el funcionario correspondiente para este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Despacho Ministerio de Minas y Energía'),
        ),
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='despacho_secretario_general',
            field=models.ForeignKey(blank=True, help_text='Seleccione el funcionario correspondiente para este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Despacho del Secretario General'),
        ),
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='despacho_viceministro_energia',
            field=models.ForeignKey(blank=True, help_text='Seleccione el funcionario correspondiente para este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Despacho Viceministro de Energía'),
        ),
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='grupo_asuntos_legislativos',
            field=models.ForeignKey(blank=True, help_text='Seleccione el funcionario correspondiente para este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Grupo de Asuntos Legislativos'),
        ),
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='grupo_comunicacion_prensa',
            field=models.ForeignKey(blank=True, help_text='Seleccione el funcionario correspondiente para este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Grupo de Comunicación y Prensa'),
        ),
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='grupo_gestion_estrategica_sector_extractivo',
            field=models.ForeignKey(blank=True, help_text='Seleccione el funcionario correspondiente para este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Grupo de Gestión Estratégica del Sector Extractivo'),
        ),
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='grupo_unidad_resultados',
            field=models.ForeignKey(blank=True, help_text='Seleccione el funcionario correspondiente para este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Grupo Unidad de Resultados'),
        ),
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='oficina_asesora_juridica',
            field=models.ForeignKey(blank=True, help_text='Seleccione el funcionario correspondiente para este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Oficina Asesora de Jurídica'),
        ),
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='oficina_asuntos_ambientales_sociales',
            field=models.ForeignKey(blank=True, help_text='Seleccione el funcionario correspondiente para este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Oficina de Asuntos Ambientales y Sociales'),
        ),
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='oficina_asuntos_regulatorios_empresariales',
            field=models.ForeignKey(blank=True, help_text='Seleccione el funcionario correspondiente para este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Oficina de Asuntos Regulatorios y Empresariales'),
        ),
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='oficina_control_interno',
            field=models.ForeignKey(blank=True, help_text='Seleccione el funcionario correspondiente para este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Oficina de Control Interno'),
        ),
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='oficina_planeacion_gestion_internacional',
            field=models.ForeignKey(blank=True, help_text='Seleccione el funcionario correspondiente para este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Oficina de Planeación y Gestión Internacional'),
        ),
    ]
