# Generated by Django 3.1.7 on 2021-06-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0032_auto_20210629_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organigramainteractivopage',
            old_name='despacho_ministerio_minas_energía',
            new_name='despacho_ministerio_minas_energia',
        ),
    ]
