# Generated by Django 3.1.7 on 2021-06-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0033_auto_20210629_1851'),
        ('ministerio', '0025_auto_20210629_1134'),
    ]

    operations = [
    ]
