# Generated by Django 3.1.7 on 2021-07-19 22:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('ministerio', '0035_auto_20210713_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiapage',
            name='history',
        ),
        migrations.RemoveField(
            model_name='historiapage',
            name='video_description',
        ),
        migrations.AddField(
            model_name='historiapage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Imagen que representa la sección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='historiapage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='historiapage',
            name='intro_title',
            field=models.CharField(default='Historia', max_length=254, verbose_name='Título de la sección'),
        ),
        migrations.AlterField(
            model_name='culturacorporativapage',
            name='corporate_culture',
            field=wagtail.core.fields.StreamField([('Cultura_Corporativa', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='TÃ\xadtulo que describe el elemento de cultura corporativa.', label='TÃ\xadtulo del Elemento', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen que representa el elemento de cultura corporativa.', label='Imagen', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Este atributo proporciona informaciÃ³n alternativa para una imagen si un usuario, por alguna razÃ³n, no puede verla (debido a una conexiÃ³n lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla).', label='Texto alternativo', required=False)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ul', 'ol', 'italic', 'link', 'hr'], help_text='Texto descriptivo del elemento de cultura corporativa.', icon='fa-paragraph', label='DescripciÃ³n', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Cultura Corporativa'),
        ),
        migrations.AlterField(
            model_name='culturacorporativapage',
            name='corporate_culture_objetives',
            field=wagtail.core.fields.StreamField([('Objetivos_de_Calidad', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='TÃ\xadtulo que describe el elemento de objetivos de calidad.', label='TÃ\xadtulo del Elemento', required=True)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ul', 'ol', 'italic', 'link', 'hr'], help_text='Texto descriptivo del elemento de objetivos de calidad.', icon='fa-paragraph', label='DescripciÃ³n', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Objetivos de Calidad'),
        ),
        migrations.AlterField(
            model_name='historiapage',
            name='link_video',
            field=models.URLField(blank=True, help_text='Si completa este campo, la imagen no será presentada. El link requerido debe tener el siguiente formato https://www.youtube.com/embed/lkizzbz2ci85', verbose_name='Video'),
        ),
    ]
