# Generated by Django 3.1.10 on 2021-07-23 11:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('ministerio', '0036_auto_20210719_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionDeLaInformacion',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='culturacorporativapage',
            name='corporate_culture',
            field=wagtail.core.fields.StreamField([('Cultura_Corporativa', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Título que describe el elemento de cultura corporativa.', label='Título del Elemento', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen que representa el elemento de cultura corporativa.', label='Imagen', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla).', label='Texto alternativo', required=False)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ul', 'ol', 'italic', 'link', 'hr'], help_text='Texto descriptivo del elemento de cultura corporativa.', icon='fa-paragraph', label='Descripción', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Cultura Corporativa'),
        ),
        migrations.AlterField(
            model_name='culturacorporativapage',
            name='corporate_culture_objetives',
            field=wagtail.core.fields.StreamField([('Objetivos_de_Calidad', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Título que describe el elemento de objetivos de calidad.', label='Título del Elemento', required=True)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ul', 'ol', 'italic', 'link', 'hr'], help_text='Texto descriptivo del elemento de objetivos de calidad.', icon='fa-paragraph', label='Descripción', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Objetivos de Calidad'),
        ),
    ]
