# Generated by Django 3.1.10 on 2021-08-03 14:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('ministerio', '0039_auto_20210729_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesosprocedimientospage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Descripción del proceso o procedimiento.', null=True, verbose_name='Descripción del proceso o procedimiento'),
        ),
        migrations.AlterField(
            model_name='procesosprocedimientospage',
            name='image',
            field=models.ForeignKey(help_text='Imagen del mapa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen del mapa.'),
        ),
        migrations.AlterField(
            model_name='procesosprocedimientospage',
            name='link_mapa',
            field=models.URLField(blank=True, verbose_name='Link del mapa.'),
        ),
        migrations.AlterField(
            model_name='procesosprocedimientospage',
            name='systems',
            field=wagtail.core.fields.StreamField([('Procesos_y_Procedimientos', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Nombre del sistema al que se enlazará.', label='Nombre del sistema', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen del sistema.', label='Imagen del sistema', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Descripción del sistema.', label='Descripción del sistema', required=True)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Link a página externa.', label='Link a página externa', required=False))]))], blank=True, verbose_name='Procesos y Procedimientos'),
        ),
    ]
