# Generated by Django 3.1.13 on 2021-09-02 23:49

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('ministerio', '0043_auto_20210813_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturacorporativapage',
            name='corporate_culture',
            field=wagtail.core.fields.StreamField([('Cultura_Corporativa', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='TÃ\xadtulo que describe el elemento de cultura corporativa.', label='TÃ\xadtulo del Elemento', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen que representa el elemento de cultura corporativa.', label='Imagen', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Este atributo proporciona informaciÃ³n alternativa para una imagen si un usuario, por alguna razÃ³n, no puede verla (debido a una conexiÃ³n lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla).', label='Texto alternativo', required=False)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ul', 'ol', 'italic', 'link', 'hr'], help_text='Texto descriptivo del elemento de cultura corporativa.', icon='fa-paragraph', label='DescripciÃ³n', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Cultura Corporativa'),
        ),
        migrations.AlterField(
            model_name='culturacorporativapage',
            name='corporate_culture_objetives',
            field=wagtail.core.fields.StreamField([('Objetivos_de_Calidad', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='TÃ\xadtulo que describe el elemento de objetivos de calidad.', label='TÃ\xadtulo del Elemento', required=True)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ul', 'ol', 'italic', 'link', 'hr'], help_text='Texto descriptivo del elemento de objetivos de calidad.', icon='fa-paragraph', label='DescripciÃ³n', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Objetivos de Calidad'),
        ),
        migrations.AlterField(
            model_name='gestiondelainformacion',
            name='elementos',
            field=wagtail.core.fields.StreamField([('Elementos', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='TÃ\xadtulo que describe el elemento.', label='TÃ\xadtulo del Elemento', required=True)), ('svg_image', wagtailsvg.blocks.SvgChooserBlock(help_text='Imagen que representa el elemento.', label='Imagen', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Este atributo proporciona informaciÃ³n alternativa para una imagen si un usuario, por alguna razÃ³n, no puede verla (debido a una conexiÃ³n lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla).', label='Texto alternativo', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Link a pÃ¡gina externa.', label='Link a pÃ¡gina externa', required=False)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ul', 'ol', 'italic', 'link', 'hr'], help_text='Texto descriptivo del elemento.', icon='fa-paragraph', label='DescripciÃ³n', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Adicione elementos informativos'),
        ),
        migrations.AlterField(
            model_name='gestiondelainformacion',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Imagen que representa la secciÃ³n', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='gestiondelainformacion',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='IntroducciÃ³n de la secciÃ³n', null=True, verbose_name='IntroducciÃ³n'),
        ),
        migrations.AlterField(
            model_name='procesosprocedimientospage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='DescripciÃ³n del proceso o procedimiento.', null=True, verbose_name='DescripciÃ³n del proceso o procedimiento'),
        ),
        migrations.AlterField(
            model_name='procesosprocedimientospage',
            name='systems',
            field=wagtail.core.fields.StreamField([('Procesos_y_Procedimientos', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Nombre del sistema al que se enlazarÃ¡.', label='Nombre del sistema', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen del sistema.', label='Imagen del sistema', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='DescripciÃ³n del sistema.', label='DescripciÃ³n del sistema', required=True)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Link a pÃ¡gina externa.', label='Link a pÃ¡gina externa', required=False))]))], blank=True, verbose_name='Procesos y Procedimientos'),
        ),
    ]
