# Generated by Django 3.1.13 on 2021-09-03 13:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('ministerio', '0044_auto_20210902_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturacorporativapage',
            name='corporate_culture',
            field=wagtail.core.fields.StreamField([('Cultura_Corporativa', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Título que describe el elemento de cultura corporativa', label='Título del Elemento', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen que representa el elemento de cultura corporativa', label='Imagen', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', label='Texto alternativo', required=False)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ul', 'ol', 'italic', 'link', 'hr'], help_text='Texto descriptivo del elemento de cultura corporativa', icon='fa-paragraph', label='Descripción', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Cultura Corporativa'),
        ),
        migrations.AlterField(
            model_name='culturacorporativapage',
            name='corporate_culture_objetives',
            field=wagtail.core.fields.StreamField([('Objetivos_de_Calidad', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Título que describe el elemento de objetivos de calidad', label='Título del Elemento', required=True)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ul', 'ol', 'italic', 'link', 'hr'], help_text='Texto descriptivo del elemento de objetivos de calidad', icon='fa-paragraph', label='Descripción', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Objetivos de Calidad'),
        ),
        migrations.AlterField(
            model_name='gestiondelainformacion',
            name='elementos',
            field=wagtail.core.fields.StreamField([('Elementos', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Título que describe el elemento', label='Título del Elemento', required=True)), ('svg_image', wagtailsvg.blocks.SvgChooserBlock(help_text='Imagen', label='Imagen', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', label='Texto alternativo', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Link a página externa', label='Link a página externa', required=False)), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ul', 'ol', 'italic', 'link', 'hr'], help_text='Texto descriptivo del elemento', icon='fa-paragraph', label='=Descripción', required=False, template='blocks/paragraph_block.html'))]))], blank=True, verbose_name='Adicione elementos informativos'),
        ),
        migrations.AlterField(
            model_name='gestiondelainformacion',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='gestiondelainformacion',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='procesosprocedimientospage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Descripción del proceso o procedimiento', null=True, verbose_name='Descripción del proceso o procedimiento'),
        ),
        migrations.AlterField(
            model_name='procesosprocedimientospage',
            name='image',
            field=models.ForeignKey(help_text='Imagen del mapa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen del mapa'),
        ),
        migrations.AlterField(
            model_name='procesosprocedimientospage',
            name='link_mapa',
            field=models.URLField(blank=True, verbose_name='Link del mapa'),
        ),
        migrations.AlterField(
            model_name='procesosprocedimientospage',
            name='systems',
            field=wagtail.core.fields.StreamField([('Procesos_y_Procedimientos', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Nombre del sistema al que se enlazará', label='Nombre del sistema', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen del sistema', label='Imagen del sistema', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Descripción del sistema', label='Descripción del sistema', required=True)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Link a página externa', label='Link a página externa', required=False))]))], blank=True, verbose_name='Procesos y Procedimientos'),
        ),
    ]
