# Generated by Django 3.1.13 on 2021-09-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0045_auto_20210903_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturacorporativapage',
            name='section_title',
            field=models.CharField(default='Objetivos de calidad', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
