# Generated by Django 3.1.13 on 2021-09-27 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0047_auto_20210927_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesosprocedimientospage',
            name='description',
        ),
    ]
