# Generated by Django 3.1.13 on 2021-09-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0048_remove_procesosprocedimientospage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesosprocedimientospage',
            name='alt_text',
            field=models.TextField(blank=True, help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', verbose_name='Texto alternativo'),
        ),
    ]
