# Generated by Django 3.1.13 on 2021-09-28 00:14

import apps.ministerio.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0050_auto_20210927_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlinternopage',
            name='acordeon',
            field=wagtail.core.fields.StreamField([('Acordeon', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento.', label='Título del elemento', required=True)), ('description', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'hr'], help_text='Texto descriptivo.', icon='fa-paragraph', label='Descripción', required=True))]))], blank=True, verbose_name='Acordeon'),
        ),
        migrations.AlterField(
            model_name='controlinternopage',
            name='element',
            field=wagtail.core.fields.StreamField([('Elemento', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento.', label='Título del elemento', required=True)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono de la parte superior izquierda del elemento, solo se acepta imágenes en formato SVG.', label='Icono del elemento', required=True)), ('description', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'hr'], help_text='Texto descriptivo.', icon='fa-paragraph', label='Descripción', required=True)), ('background_color', wagtail.core.blocks.CharBlock(help_text='Color de fondo para el elemento en formato hexadecimal. Ejemplo: #5A0C6D', label='Color de fondo', max_length=7, required=True)), ('text_color', wagtail.core.blocks.CharBlock(help_text='Color de texto en formato hexadecimal. Ejemplo: #5A0C6D', label='Color de texto', max_length=7, required=True))]))], blank=True, verbose_name='Elementos'),
        ),
        migrations.AlterField(
            model_name='controlinternopage',
            name='subsections',
            field=wagtail.core.fields.StreamField([('Subseccion', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título de la subsección.', label='Título de la subsección', required=True)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono de la subsección, solo se acepta imágenes en formato SVG.', label='Icono de la subsección', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local.', label='Link a página local', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Complete este campo si desea enlazar este elemento con una página externa.Si este campo está completo, no se tendrá en cuenta el link a página local.', label='Link a página externa:', required=False))]))], blank=True, verbose_name='Elementos'),
        ),
        migrations.AlterField(
            model_name='funcionariopage',
            name='staff_list',
            field=wagtail.core.fields.StreamField([('Personal', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Título del elemento.', label='Nombre del funcionario', required=True)), ('position', wagtail.core.blocks.CharBlock(help_text='Título del elemento.', label='Cargo del funcionario', required=True)), ('personal', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('group', wagtail.core.blocks.CharBlock(blank=False, help_text='Nombre del grupo.', label='Nombre del grupo', required=False)), ('name', wagtail.core.blocks.CharBlock(blank=False, help_text='Nombre del funcionario a cargo del grupo.', label='Nombre del funcionario', required=False))], closed=False, icon='user', value_class=apps.ministerio.blocks.LinkStructValue), required=True))]))], blank=True, verbose_name='Grupos y Personas'),
        ),
        migrations.AlterField(
            model_name='procesosprocedimientospage',
            name='systems',
            field=wagtail.core.fields.StreamField([('Procesos_y_Procedimientos', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Nombre del sistema al que se enlazará', label='Nombre del sistema', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen del sistema', label='Imagen del sistema', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Este atributo proporciona información alternativa para una imagen si un usuario, por alguna razón, no puede verla (debido a una conexión lenta, un error en el atributo src o si el usuario utiliza un lector de pantalla)', label='Texto alternativo', required=False)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Descripción del sistema', label='Descripción del sistema', required=True)), ('button_title', wagtail.core.blocks.CharBlock(help_text='Título del boton', label='Título del boton', required=True)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Link a página externa', label='Link a página externa', required=False))]))], blank=True, verbose_name='Procesos y Procedimientos'),
        ),
    ]
