# Generated by Django 3.1.13 on 2021-09-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0054_auto_20210929_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestiondelainformacion',
            name='elements_title',
            field=models.CharField(default='Sistemas de información misional', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
