# Generated by Django 3.1.13 on 2021-10-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0062_auto_20211007_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuestogeneralasignadopage',
            old_name='assigned_taps_list',
            new_name='assigned_tabs_list',
        ),
        migrations.RenameField(
            model_name='presupuestogeneralasignadopage',
            old_name='assigned_taps_list_title',
            new_name='assigned_tabs_list_title',
        ),
        migrations.RenameField(
            model_name='presupuestogeneralasignadopage',
            old_name='general_taps_list',
            new_name='general_tabs_list',
        ),
        migrations.RenameField(
            model_name='presupuestogeneralasignadopage',
            old_name='general_taps_list_title',
            new_name='general_tabs_list_title',
        ),
        migrations.RenameField(
            model_name='presupuestopage',
            old_name='taps_list',
            new_name='tabs_list',
        ),
        migrations.RenameField(
            model_name='presupuestopage',
            old_name='taps_list_title',
            new_name='tabs_list_title',
        ),
    ]
