# Generated by Django 3.1.13 on 2021-10-14 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('ministerio', '0075_auto_20211013_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlinternopage',
            name='document_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='controlinternopage',
            name='planning_title',
            field=models.CharField(default='Planeación de la Gestión Independiente', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
