# Generated by Django 3.1.13 on 2021-10-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0086_documentosseguimientopage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosseguimientopage',
            name='general_tabs_list_title',
        ),
    ]
