# Generated by Django 3.1.13 on 2021-10-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0090_auto_20211020_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacionpage',
            name='intro_title',
            field=models.CharField(default='Contratación', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
