# Generated by Django 3.1.13 on 2021-10-25 01:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0002_svg_edit_code'),
        ('ministerio', '0092_auto_20211022_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacionpage',
            name='amounts_intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='contratacionpage',
            name='amounts_logo',
            field=models.ForeignKey(help_text='Icono del componente en formato SVG', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg', verbose_name='Icono'),
        ),
    ]
