# Generated by Django 3.1.13 on 2021-10-25 01:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0093_auto_20211024_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacionpage',
            name='amounts_list',
            field=wagtail.core.fields.StreamField([('Elementos', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(help_text='Seleccione un documento', label='Documento', required=False))]))], blank=True, verbose_name='Documentos'),
        ),
    ]
