# Generated by Django 3.1.13 on 2021-10-25 02:49

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0094_auto_20211024_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacionpage',
            name='amounts_list',
            field=wagtail.core.fields.StreamField([('Documento', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(help_text='Seleccione un documento', label='Documento', required=False))]))], blank=True, verbose_name='Documentos'),
        ),
        migrations.AlterField(
            model_name='contratacionpage',
            name='menu_list',
            field=wagtail.core.fields.StreamField([('Menu', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del portafolio, políticas y/o protocolos de servicio ', label='Título', required=True)), ('main_description', wagtail.core.blocks.RichTextBlock(help_text='Descripción principal del portafolio, políticas y/o protocolos de servicio ', label='Descripción principal ', required=True))]))], blank=True, verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='contratacionpage',
            name='pbi_endpoint',
            field=models.URLField(blank=True, help_text='Link de acceso al tablero Power BI', verbose_name='Link tablero Power BI'),
        ),
    ]
