# Generated by Django 3.1.13 on 2021-11-11 20:21

import apps.common.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('ministerio', '0103_auto_20211108_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistóricoPlaneacionEstratégicaSectorialPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('data_list', wagtail.core.fields.StreamField([('Lista', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True)), ('subitems', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True))]), blank=True, help_text='Lista de elementos', label='Lista de elementos', required=False))]))], blank=True, verbose_name='Lista')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='contratacionpage',
            name='menu_list',
            field=wagtail.core.fields.StreamField([('Menu', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del portafolio, políticas y/o protocolos de servicio ', label='Título', required=True)), ('main_description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True))]))], blank=True, verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='planesprogramaspage',
            name='plans_list',
            field=wagtail.core.fields.StreamField([('Objetivos', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Planes y Programas', label='Título', required=True)), ('subitems', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(blank=False, help_text='Título del elemento', label='Título del elemento', required=True)), ('subtitle', wagtail.core.blocks.TextBlock(blank=False, help_text='Subtítulo del elemento', label='Subtítulo del elemento', required=True)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Link a página local', label='Link a página local', required=False)), ('documents_block', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(blank=False, help_text='Título del elemento', label='Título del elemento', required=True)), ('documents', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(blank=False, help_text='Título del documento', label='Título del documento', required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(help_text='Seleccione un documento', label='Documento', required=True))]), blank=True, help_text='Lista de documentos', icon='list-ul', label='Lista de documentos', required=False))]), blank=True, help_text='Lista de elementos', icon='list-ul', label='Lista de elementos', required=False))]), blank=True, help_text='Lista de elementos', icon='list-ul', label='Lista de elementos', required=False, value_class=apps.common.blocks.LinkStructValue))]))], blank=True, verbose_name='Lista de objetivos'),
        ),
    ]
