# Generated by Django 3.1.13 on 2021-11-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0130_auto_20211113_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politicasobjetivoscalidadpage',
            old_name='monitoring_main_intro',
            new_name='monitoring_main',
        ),
        migrations.RenameField(
            model_name='politicasobjetivoscalidadpage',
            old_name='monitoring_second_intro',
            new_name='monitoring_second',
        ),
    ]
