# Generated by Django 3.1.13 on 2021-11-13 22:32

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0131_auto_20211113_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicasobjetivoscalidadpage',
            name='test',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección dos', null=True, verbose_name='Introducción dos'),
        ),
    ]
