# Generated by Django 3.1.13 on 2021-11-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0132_politicasobjetivoscalidadpage_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicasobjetivoscalidadpage',
            name='test',
        ),
    ]
