# Generated by Django 3.1.13 on 2021-11-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0133_remove_politicasobjetivoscalidadpage_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicasobjetivoscalidadpage',
            name='audit_title',
            field=models.CharField(default='Auditorías', max_length=254, verbose_name='Título de la sección'),
        ),
    ]
