# Generated by Django 3.1.13 on 2021-11-13 23:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0134_politicasobjetivoscalidadpage_audit_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicasobjetivoscalidadpage',
            name='audit_list',
            field=wagtail.core.fields.StreamField([('Auditoria', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del portafolio, políticas y/o protocolos de servicio ', label='Título', required=True)), ('main_description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True))]))], blank=True, verbose_name='Auditoías'),
        ),
    ]
