# Generated by Django 3.1.13 on 2021-11-22 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('ministerio', '0140_auto_20211121_1907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcesosProcedimientosPage',
            new_name='MipgPage',
        ),
    ]
