# Generated by Django 3.1.13 on 2021-11-29 12:44

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0154_planaccionanualpage_programaauditoriainternaindependientepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaccionanualpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
    ]
