# Generated by Django 3.1.13 on 2021-12-05 23:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0159_gestiontalentohumanopage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestiontalentohumanopage',
            name='menu_title',
        ),
        migrations.AlterField(
            model_name='gestiontalentohumanopage',
            name='menu_list',
            field=wagtail.core.fields.StreamField([('Elementos', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('main_description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True))]))], blank=True, verbose_name='Menú'),
        ),
    ]
