# Generated by Django 3.1.13 on 2021-12-05 23:55

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0160_auto_20211205_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestiontalentohumanopage',
            name='cards_intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Introducción de la sección', null=True, verbose_name='Introducción'),
        ),
    ]
