# Generated by Django 3.1.13 on 2021-12-06 00:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0162_gestiontalentohumanopage_manual_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestiontalentohumanopage',
            name='post_list',
            field=wagtail.core.fields.StreamField([('Elementos', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento que será mostrado al publico', label='Título', required=True)), ('subitems', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.RichTextBlock(help_text='Breve descripción', icon='fa-paragraph', label='Descripción', required=False))]), blank=True, help_text='Lista de elementos que se presentaran', label='Lista de elementos', required=False))]))], blank=True, verbose_name='Acordeón'),
        ),
    ]
