# Generated by Django 3.1.13 on 2021-12-25 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('ministerio', '0163_auto_20211205_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='organigramainteractivopage',
            name='document_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Documento'),
        ),
    ]
