# Generated by Django 3.1.13 on 2022-03-31 19:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0166_auto_20220324_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacionpage',
            name='menu_list',
            field=wagtail.core.fields.StreamField([('Menu', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('main_description', wagtail.core.blocks.RichTextBlock(help_text='Si desea que se muestre el icono NO ! complete este campo, dejelo vacio.', label='Descripción', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Complete este campo si desea enlazar este elemento con una página local', label='Link a página local', required=False)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=False)), ('icono', wagtailsvg.blocks.SvgChooserBlock(help_text='Icono del elemento que será mostrado al publico, solo imágenes en formato SVG.', label='Icono', required=False))]))], blank=True, verbose_name='Items'),
        ),
    ]
