# Generated by Django 3.1.13 on 2022-04-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0167_auto_20220330_0057'),
        ('ministerio', '0167_auto_20220331_1435'),
    ]

    operations = [
    ]
