# Generated by Django 3.1.13 on 2022-04-12 21:36

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0168_merge_20220401_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestiontalentohumanopage',
            old_name='admin_intro',
            new_name='sheets_intro2',
        ),
        migrations.RemoveField(
            model_name='gestiontalentohumanopage',
            name='admin_list',
        ),
        migrations.RemoveField(
            model_name='gestiontalentohumanopage',
            name='admin_title',
        ),
        migrations.AddField(
            model_name='gestiontalentohumanopage',
            name='sheets_list2',
            field=wagtail.core.fields.StreamField([('Elementos', wagtail.core.blocks.StructBlock([('titulo', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('subitems', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(help_text='Seleccione un documento', label='Documento', required=False)), ('date', wagtail.core.blocks.CharBlock(help_text='Fecha formato dd/mm/aaaa', label='Fecha', required=True))]), blank=True, help_text='Lista de elementos', label='Lista de elementos', required=False))]))], blank=True, verbose_name='Vinculación a Terceros – Cancelación del Registro Público de Carrera Administrativa:'),
        ),
        migrations.AddField(
            model_name='gestiontalentohumanopage',
            name='sheets_title2',
            field=models.CharField(default='Vinculación a Terceros – Cancelación del Registro Público de Carrera Administrativa ', max_length=254, verbose_name='Título de la sección'),
        ),
        migrations.AlterField(
            model_name='gestiontalentohumanopage',
            name='sheets_list',
            field=wagtail.core.fields.StreamField([('Elementos', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Título del elemento', label='Título', required=True)), ('intro', wagtail.core.blocks.RichTextBlock(help_text='Introducción', label='Introduccion', required=False)), ('piedp', wagtail.core.blocks.RichTextBlock(help_text='Pie de pagina', label='Pie de pagina', required=False)), ('subitems', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('aplicacion', wagtail.core.blocks.CharBlock(help_text='Aplicacion', label='Aplicacion', required=False)), ('name', wagtail.core.blocks.CharBlock(help_text='Nombre', label='Nombre', required=True)), ('position', wagtail.core.blocks.RichTextBlock(help_text='Descripción', label='Descripción', required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(help_text='Seleccione un documento', label='Documento', required=False)), ('date', wagtail.core.blocks.CharBlock(help_text='Fecha formato dd/mm/aaaa', label='Fecha', required=True))]), blank=True, help_text='Lista de elementos', label='Lista de elementos', required=False))]))], blank=True, verbose_name='Hojas de Vida Aspirantes'),
        ),
    ]
