# Generated by Django 3.1.13 on 2022-04-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio', '0170_funcionariopage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariopage',
            name='position',
            field=models.CharField(help_text='Cargo del funcionario.', max_length=255, null=True, verbose_name='Cargo del funcionario'),
        ),
    ]
